grafana:
  enabled: true
  service:
    type: NodePort
    nodePort: 30231
  defaultDashboardsEnabled: true
  deleteDatasources:
    - name: Alertmanager
      orgId: 1
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 300m, memory: 384Mi}
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
      alertmanager:
        enabled: false
  grafana.ini:
    analytics:
      check_for_updates: false
      reporting_enabled: false
    users:
      default_theme: dark
