fullnameOverride: kube-prometheus-stack

alertmanager:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {cpu: 300m, memory: 384Mi}

prometheus:
  service:
    type: NodePort
    nodePort: 30230
  prometheusSpec:
    scrapeInterval: 15s
    evaluationInterval: 30s
    retention: 12h
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    resources:
      requests: {cpu: 150m, memory: 512Mi}
      limits: {cpu: 1000m, memory: 1536Mi}
    additionalScrapeConfigs:
      - job_name: taskboard-backend-fallback
        scrape_interval: 15s
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names: [capstone]
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: taskboard-backend
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
