apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard.fullname" . }}-backend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app: taskboard-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "taskboard.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
{{- if .Values.backend.compatibilityServiceName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.compatibilityServiceName }}
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-compat
spec:
  type: ClusterIP
  selector:
    {{- include "taskboard.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
{{- end }}
