apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskboard.fullname" . }}-frontend
  labels:
    {{- include "taskboard.labels" . | nindent 4 }}
    app: taskboard-frontend
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "taskboard.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
